---
# Example users list for Ansible Users playbook
# Update the user information below and rename this file to users_list.yml prior to running the users.yml playbook

# All Users should follow the same format:
# {name: 'NAME', password: 'HASHED PASSWORD', groups: ['GROUPS'], system: no, shell: '/bin/bash'}
# name: put the username for the user here in single quotes
# password: put the user's password here in a hashed format, use the command: mkpasswd -m sha512crypt
# groups: put which groups the user should belong to here, in single quotes inside brackets, sudo is the admin group, leave blank if none are needed
# system: if the user is an actual user set system to no, if the user is for an app to use set system to yes
# shell: set to '/bin/bash' for a real user, set to '/bin/false' for a system user that doesn't need remote access

# Each user requires a matching id_rsa.pub file in the 'files' folder
# If the user will not need to login remotely still include an empty id_rsa.pub file in their name

user_details:
  - {name: 'ex_user', password: '$6$EzVai3Z4s$130d5Xk9BGxLMI0QK8RpqsZmIxqC8i12Rk34zyQ/bbwki4ZUVpG2lWiFUaDBwUOI1gQdrl0Ez/nVgobbhDH/X.', groups: ['sudo'], system: no, shell: '/bin/bash'}
#  - {name: '$EX_USER2', password: '$HASHED_PASSWORD', groups: ['sudo'], system: no, shell: '/bin/bash'}

# System users can be added below
  - {name: 'exporter_user', password: '', groups: [''], system: yes, shell: '/bin/false'}
#  - {name: 'ansible_user', password: '', groups: ['sudo'], system: yes, shell: '/bin/bash'}
