---
- hosts: all

  tasks:
# Searches the .htaccess file in the WordPress folder for the '# BEGIN PASSWORD' marker and then deletes everything between it and the END marker
  - name: Remove password section from .htaccess file
    become: true
    blockinfile:
      path: /var/www/wordpress/.htaccess
      marker: "# {mark} PASSWORD"
      block: ""