---
- hosts: all

  tasks:
# Check for and run updates
  - name: Update apt repo and cache on all servers
    become: true
    apt: 
      name: python3-passlib
      state: present
      update_cache: true

  - name: Check if a htpasswd.users file already exists
    stat:
      path: /etc/apache2/htpasswd.users
    register: file_check
# The password listed in this task is done in an 'unsecure' manner in plain text for ease of use
# This method for securing websites should not be considered secure and is only for keeping the public away from accidental browsing
  - name: Create password file and admin user
    become: true
    htpasswd:
      path: /etc/apache2/htpasswd.users
      name: admin
      password: 'casat!!279'
      owner: root
      group: www-data
      mode: '0640'
    when: not file_check.stat.exists

  - name: Update .htaccess file to use Apache password
    become: true
    blockinfile:
      path: /var/www/wordpress/.htaccess
      marker: "# {mark} PASSWORD"
      block: |
        AuthType Basic
        AuthName "Authorized Users"
        AuthUserFile /etc/apache2/htpasswd.users
        Require valid-user

  - name: Restart Apache for password to take effect
    service:
      name: apache2
      state: restarted

    