---
- hosts: all
  become: true

  tasks:
  
  - name: "Update repository cache"
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 86400 #One day
    
  - name: "Upgrade packages"
    apt:
      upgrade: 'yes'
      force_apt_get: yes
    register: apt_updates

  - name: "Remove deprecated packages"
    apt:
      autoremove: yes

  - name: Reboot the server
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime


